version: '3'

services:
  mariadb:
    image: bitnami/mariadb:latest
    ports:
      - "3306:3306"
    container_name: moodle-dockerized-mariadb
    environment:
      ALLOW_EMPTY_PASSWORD: yes
      MARIADB_USER: bn_moodle
      MARIADB_PASSWORD: bitnami
      MARIADB_DATABASE: bitnami_moodle
      MARIADB_ROOT_PASSWORD: bitnami
    networks:
      - moodle-dockerized-moodle-network
    volumes:
      - mariadb_data:/bitnami/mariadb

  moodle:
    image: bitnami/moodle:latest
    container_name: moodle-dockerized-moodle
    ports:
      - "8080:8080"
      - "8443:8443"
    environment:
      ALLOW_EMPTY_PASSWORD: yes
      MOODLE_DATABASE_HOST: mariadb
      MOODLE_DATABASE_PORT_NUMBER: 3306
      MOODLE_DATABASE_USER: bn_moodle
      MOODLE_DATABASE_PASSWORD: bitnami
      MOODLE_DATABASE_NAME: bitnami_moodle
    networks:
      - moodle-dockerized-moodle-network
    volumes:
      - moodle_data:/bitnami/moodle
      - moodledata_data:/bitnami/moodledata
    depends_on:
      mariadb:
        condition: service_started

networks:
  moodle-dockerized-moodle-network:

volumes:
  mariadb_data:
  moodle_data:
  moodledata_data:
